### PR TITLE
fix: Reduce warnings in load mode

### PR DESCRIPTION
**Pull request by martinalbert**
## Description

Removes number of scopes check.

## Motivation and Context

Unnecessary warnings - there could be cases where recording fixture can be empty.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the documentation accordingly. If you are changing **code related to user secrets** you need to really make sure that [security documentation](SECURITY.md) is correct.
- [x] I have read the **CONTRIBUTION_GUIDE** document.
- [x] I haven't repeated the code. (DRY)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by freaz** [comment]
I do not understand it. Can you show me recording which will trigger the warning please?

**Comment by martinalbert** [comment]
I went through `define` function in more detail and this won't ever trigger a warning. Every valid recording passed in `define` gets intercepted, so length of those arrays should always match. 

Sorry about this confusion, I should have checked it sooner. I propose to modify this check to warn only if length does not match. It might not be necessary, but we process the recordings, so it might be handy when someone accidentally removes recording in `beforeRecordingLoad` hook or if `define` would change its implementation. What do you think?

**Comment by freaz** [comment]
Thats fine, I just wasn't able to understand what I am not seeing. Si I guess this PR can be closed and we will need to find other way.

**Comment by martinalbert** [comment]
I can remove the warning for now, it's not useful anyway.

**Comment by freaz** [comment]
And would it be possible to print it only off in record mode?

**Comment by freaz** [comment]
Damn, I was in different context. I would remove it, because there are cases when recording should be empty.

**Review by freaz — APPROVED** [review]

**Pull request merged**
